# Поддержка цветов
set-option -g default-terminal "tmux-256color"

# Поведение окон
set-window-option -g aggressive-resize on
set-option -g renumber-windows on

# Поддержка мыши
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# История
set-option -g history-file "/home/varga/.tmux/.history"

# История прокрутки
set-option -g history-limit 50000

# Переход в режим управления
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# Перезагрузка конфигов
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# Автоматическое сохранение сессии
set -g @continuum-save-interval '60'
set -g @resurrect-strategy-vim 'session'

# Эмуляция vim
set-option -g @shell_mode 'vi'
set-window-option -g mode-keys vi
set-option -g status-keys vi

# Задержка переключения режимов vim
set-option -s escape-time 0

# Режим копирования
bind -T copy-mode-vi 'v' send-keys -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-selection
bind -T copy-mode-vi 'r' send-keys -X rectangle-toggle
unbind i
bind i run "xsel -o --clipboard | tmux load-buffer - ; tmux paste-buffer"

# Создать сплит
bind v split-window -h
bind s split-window -v

# Изменение размера панели
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Цвета панелей
# Стиль активного/неактивного окна
set -g window-style 'fg=colour247'
set -g window-active-style 'fg=#17f018'

## Граница панели
set -g pane-border-bg default
set -g pane-border-fg colour238
set -g pane-active-border-bg default
set -g pane-active-border-fg colour103

# Навигация по окнам
bind p previous-window
bind n next-window

# Изменение порядка окон
bind -r < swap-window -t -1
bind -r > swap-window -t +1

# Переименовать окно
unbind ,
bind-key , command-prompt -p (rename-window) "rename-window '%%'"

# Заголовок окна
set-option -g set-titles on
set-option -g set-titles-string '#S:#I.#P #W'
set-window-option -g automatic-rename on

# Сообщения
set-window-option -g mode-bg black
set-window-option -g mode-fg colour214
set-option -g message-bg black
set-option -g message-fg colour214

# Панель состояния
set-option -g status-bg black
set-option -g status-fg colour237
set-option -g status-attr dim

set-window-option -g window-status-fg colour237
set-window-option -g window-status-bg black
set-window-option -g window-status-attr dim

set-window-option -g window-status-current-fg colour103
set-window-option -g window-status-current-bg black
set-window-option -g window-status-current-attr dim

set-option -g status-interval 15
set-option -g status-left-length 30
set-option -g status-right-length 70
set-option -g status-justify right
set-option -g @online_icon "✔"
set-option -g @offline_icon "✘"

set-option -g status-left '#[fg=colour136]» #[fg=colour100,bold]#T#[default]'
set-option -g status-right '#[fg=colour136]»» #[fg=colour100,bold]#{session_group} #[fg=colour107]#{cpu_icon}#{cpu_percentage} #[fg=colour136]#(free -h |grep Mem: |tr -s " " |cut -d " " -f 2-3 |sed "s/\([[:graph:]]*\) \([[:graph:]]*\)/\2\/\1/") #[fg=colour83]#{online_status} #[fg=colour107]%R %d.%m.%y #[fg=colour100]#{battery_icon}#{battery_percentage}#[default]'
set-option -g visual-activity on
set-window-option -g monitor-activity on

# Plugins
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'tmux-plugins/tmux-cpu'
set-option -g @plugin 'tmux-plugins/tmux-battery'
set-option -g @plugin 'tmux-plugins/tmux-online-status'
set-option -g @plugin 'tmux-plugins/tmux-open'
set-option -g @plugin 'tmux-plugins/tmux-copycat'
set-option -g @plugin 'tmux-plugins/tmux-yank'
set-option -g @plugin 'tmux-plugins/tmux-resurrect'
set-option -g @plugin 'tmux-plugins/tmux-continuum'
set-option -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'
